apiVersion: v1
kind: Pod
metadata:
  name: pod-practice1
  labels:
    app: replica-practice
spec:
  containers:
    - name: server
      image: docker.io/mcastelino/nettools
      ports:
        - name: p1 # 端口名称
          containerPort: 8080  # 容器端口
      command:
        - /root/test_mount/test_network
      env:
        - name: port
          value: '8080'
      volumeMounts:
        - name: data
          mountPath: /root/test_mount
  volumes:
    - name: data
      hostPath:
        path: /home/test_mount