stages:
  - prepare
  - test
  - build

prepare:
  stage: prepare
  script:
    - go env -w GOPROXY=https://goproxy.cn
  tags:
    - shell

test-kubelet:
  stage: test
  script:
    - sudo /usr/local/go/bin/go test minik8s/pkg/kubelet/container -cover
    - sudo /usr/local/go/bin/go test minik8s/pkg/kubelet/pod -cover
    - sudo /usr/local/go/bin/go test minik8s/pkg/kubelet/image -cover
  tags:
    - shell

test-kubectl:
  stage: test
  script:
    - echo "testing kubectl"
  tags:
    - shell

test-kubeproxy:
  stage: test
  script:
    - echo "testing kubeproxy"
    - sudo /usr/local/go/bin/go test minik8s/pkg/kubeproxy -cover
  tags:
    - shell

test-apiserver:
  stage: test
  script:
    - echo "testing apiserver"
    - sudo /usr/local/go/bin/go test minik8s/pkg/kubeapiserver/storage -cover
  tags:
    - shell

test-scheduler:
  stage: test
  script:
    - echo "testing scheduler"
    - sudo /usr/local/go/bin/go test minik8s/pkg/kubescheduler/policy -cover
    - sudo /usr/local/go/bin/go test minik8s/pkg/kubescheduler/filter -cover
  tags:
    - shell

test-serverless:
  stage: test
  script: 
    - echo "testing serverless"
    - sudo /usr/local/go/bin/go test mini-k8s/pkg/serverless/activator -cover
    - sudo /usr/local/go/bin/go test mini-k8s/pkg/serverless/function -cover
    - sudo /usr/local/go/bin/go test mini-k8s/pkg/serverless/workflow -cover
  tags:
    - shell

test-dns:
  stage: test
  script: 
    - echo "testing dns"
    - sudo /usr/local/go/bin/go test mini-k8s/pkg/kubedns/nginx -cover
  tags:
    - shell

build:
  stage: build
  script:
    - cd build
    - make all
    - sudo cp -r bin /home/gitlab-runner/$CI_COMMIT_BRANCH/
  tags:
    - shell
