apiVersion: v1
kind: Service
metadata:
  name: service-practice
spec:
  selector:
    app: replica-practice
  type: ClusterIP
  ports:
    - name: service-port1
      protocol: TCP
      port: 32345 # 对外暴露的端口
      targetPort: p1 # 转发的端口，pod对应的端口