#ApiserverAddr : 192.168.1.12:8080
#FlannelSubnet : 10.2.17.1/24
#IP            : 192.168.1.12
#Labels        :
#  - resource : gpu
ApiserverAddr : 192.168.1.14:8080
FlannelSubnet : 10.2.9.1/24
IP            : 192.168.1.14
Labels        :
  - resource : gpu