version: '1.0'
name: pipeline-test
displayName: pipeline-test
triggers:
  trigger: manual
  pr:
    branches:
      prefix:
        - ''
stages:
  - name: stage-cc6a9f8d
    displayName: test
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - step: build@golang
        name: build_golang
        displayName: Golang 构建
        golangVersion: '1.12'
        commands:
          - '# 默认使用goproxy.cn'
          - export GOPROXY=https://goproxy.cn
          - '# 输入你的构建命令'
          - echo 123123
        artifacts:
          - name: BUILD_ARTIFACT
            path:
              - ./output
        caches:
          - /go/pkg/mod
        notify: []
        strategy:
          retry: '0'
