apiVersion: v1
kind: Pod
metadata:
  name: pod2
  labels:
    app: replica-practice
spec:
  containers:
    - name: c1
      image: docker.io/mcastelino/nettools
      command:
        - /root/test_mount/test_cpu
      volumeMounts:
        - name: test-volume
          mountPath: /root/test_mount
      resources:
        limits:
                cpu: "0.5"
                memory: "100Mi"
    - name: c2
      image: docker.io/mcastelino/nettools
      command:
        - /root/test_mount/test_memory
      volumeMounts:
        - name: test-volume
          mountPath: /root/test_mount
      resources:
        limits:
                cpu: "0.5"
                memory: "100Mi"
  volumes:
    - name: test-volume
      hostPath:
        path: /home/test_mount

